### ISSUE TITLE
Log before start of KestrelHttpServer locks for 20 min before opening port (Serilog.Sinks.Logentries 3.0.0-dev-00020).

### ISSUE THREAD

**Issue by Looooopy** [serilog/serilog-sinks-logentries#12]
Hi,

When we are doing things like this at startup:

```
public class Program
{
        public static void Main(string[] args)
        {
             var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            ILogger<Program> logger = host.Services.GetService(typeof(ILogger<Program>)) as ILogger<Program>;
            logger.LogInformation($"Starting application ({hostingEnvironment.EnvironmentName})");

            host.Run();
        }
}
```
Later inside the application we doing other serilog logging.

We will get a delay of 20 minutes before we successfully start listen on our port and all logging after this seams to work as expected. 
Some threading/locking issue in Serilog.Sinks.Logentries causing this problem.
In the logging below we have turned on the "Serilog.Debugging.SelfLog.Enable(msg => Console.WriteLine(msg));" to see what serilog is doing.

**The environment:**
Docker inside AWS/Rancher
Docker image as base: microsoft/aspnetcore:1.0.1

**Log:**
```
2016-10-31 13:12:11 [Information] Starting application (Develop)
2016-10-31T13:31:16.4800960Z Exception while emitting periodic batch from Serilog.Sinks.Logentries.LogentriesSink: System.AggregateException: One or more errors occurred. (Connection timed out 54.217.226.25:20000) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection timed out 54.217.226.25:20000
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.SocketTaskExtensions.<>c.<ConnectAsync>b__3_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Sockets.TcpClient.<ConnectAsyncCorePrivate>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.TcpClient.<ConnectAsyncCorePrivate>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Sockets.TcpClient.<ConnectAsyncCorePrivate>d__62.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Serilog.Sinks.Logentries.LeClient.Connect()
   at Serilog.Sinks.Logentries.LogentriesSink.EmitBatch(IEnumerable`1 events)
   at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection timed out 54.217.226.25:20000
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.SocketTaskExtensions.<>c.<ConnectAsync>b__3_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Sockets.TcpClient.<ConnectAsyncCorePrivate>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Sockets.TcpClient.<ConnectAsyncCorePrivate>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Sockets.TcpClient.<ConnectAsyncCorePrivate>d__62.MoveNext()<---

2016-10-31 13:31:16 [Information] Overriding kestrel server urls: http://+:5000
2016-10-31 13:31:16 [Debug] Listening on: http://+:5000
[?1h=2016-10-31 13:31:16 [Debug] Hosting starting
2016-10-31 13:31:16 [Debug] Hosting started
Hosting environment: Develop
Content root path: /dotnetapp
Now listening on: http://+:5000
Application started. Press Ctrl+C to shut down.
```

We have confirmed that if we remove "Serilog.Sinks.Logentries" we don't get this delay.

Any suggestions?

**Comment by nblumhardt** [comment]
Thank you for the report, it appears that the initial connection to LE is synchronous here, which because of the long connection timeout is unfortunately holding up everything else.

We've recently updated the underlying `PeriodicBatchingSink` to no longer process the first batch synchronously. Would you mind please updating to version 2.1.1-dev-00725 and let us know whether the problem persists?

https://www.nuget.org/packages/Serilog.Sinks.PeriodicBatching/2.1.1-dev-00725

You should be able to either `Update-Package Serilog.Sinks.PeriodicBatching -Version 2.1.1-dev-00725` (Windows) or add the package to your _project.json_ and run `dotnet restore --no-cache`.

Cheers,
Nick

**Comment by kristofferahl** [comment]
We've had this problem as well... Just curious, why does it time out to begin with?

**Comment by nblumhardt** [comment]
I am not sure- I've never used Logentries. If someone is able to investigate, some help with getting this sink ship-shape would be hugely appreciated.

**Comment by Looooopy** [comment]
The problem went away i do not get any exception when using PeriodicBatchingSink 2.1.1-dev-00725.

The Serilog.Debugging.SelfLog.Enable do not log anything about that anymore and the program starts directly.

So without investigate further i would like to say it solved the issue.

**Comment by nblumhardt** [comment]
Awesome, thank you for the follow-up @Looooopy.
